# Site settings
title: Pixyll@
email: your_email@example.com
author: Beautiful Skyline
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl: ""
url: "http://it.skylines.su"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
